name: pip build windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    name: Build wheels for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          set VCPKG_BUILD_TYPE=release
          vcpkg install eigen3 cgal --triplet x64-windows
          vcpkg version
          ls C:/vcpkg/installed/x64-windows/bin
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows .
          cd ${{ github.workspace }}
          python -m pip install --user -r ext/gudhi-deploy/build-requirements.txt
          python -m pip list
      - name: Build python wheel
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows ..
          cd src/python
          cp c:/vcpkg/installed/x64-windows/bin/mpfr-6.dll gudhi/
          cp c:/vcpkg/installed/x64-windows/bin/gmp.dll gudhi/
          python setup.py bdist_wheel
          ls dist
      - name: Install and test python wheel
        run: |
          cd ${{ github.workspace }}
          cd build/src/python/dist/
          Get-ChildItem *.whl | ForEach-Object{python -m pip install --user $_.Name}
          cd ${{ github.workspace }}
          python -m pip install --user pytest
          python -m pytest src/python/test/test_alpha_complex.py
